version: "3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "kek"
      POSTGRES_PASSWORD: "lolkek"
    ports:
      - "5432:5432"
#  tomcat:
#    image: "tomcat:10.1.13-jdk17"
#    ports:
#      - "8080:8080"
#    volumes:
#      - "./webapps:/usr/local/tomcat/webapps"