version: "3"
services:
  postgres:
    image: "postgres:15.4"
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "kek"
      POSTGRES_PASSWORD: "lolkek"
    ports:
      - "5432:5432"
  juddi:
    image: "ericcong/juddi:3.3.3"
    ports:
      - "8080:8080"